{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.userList.existingSecret | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.clusterSecretStore | quote }}
  target:
    name: {{ .Values.userList.existingSecret | quote }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: userlist.txt
      remoteRef:
        key: {{ .Values.externalSecrets.userList.remoteKey | quote }}
        property: {{ .Values.externalSecrets.userList.property | quote }}
{{- end }}
