{{- if and (not .Values.userList.existingSecret) .Values.userList.createPlaceholder -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}-userlist
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
  annotations:
    pgbouncer.proxmox.local/placeholder: "true"
type: Opaque
stringData:
  userlist.txt: |
    "pgbouncer" "placeholder-set-via-existingSecret"
{{- end -}}
