apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-init-scripts
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: jenkins
data:
{{- range $path, $content := .Files.Glob "init-scripts/*.groovy" }}
  {{ base $path }}: |
    {{- $content | toString | nindent 4 }}
{{- end }}
