apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    tunnel: {{ .Values.tunnel.id }}
    credentials-file: /etc/cloudflared/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    {{- range .Values.tunnel.routes }}
      - hostname: {{ .hostname }}.{{ $.Values.tunnel.domain }}
        service: http://{{ $.Values.tunnel.traefikService }}:80
    {{- end }}
      - service: http_status:404
