all:
  children:
    dns_server:
      hosts:
        dns:
          ansible_host: 10.10.0.5
          ansible_user: root

    dns_clients:
      children:
        k3s:
          hosts:
            k8s-master-1:
              ansible_host: 10.10.0.10
            k8s-master-2:
              ansible_host: 10.10.0.11
            k8s-master-3:
              ansible_host: 10.10.0.12
            k8s-infra-1:
              ansible_host: 10.10.0.13
            k8s-infra-2:
              ansible_host: 10.10.0.14
            k8s-infra-3:
              ansible_host: 10.10.0.15
            k8s-app-1:
              ansible_host: 10.10.0.16
            k8s-app-2:
              ansible_host: 10.10.0.17
        postgres:
          hosts:
            db-1:
              ansible_host: 10.10.0.20
            db-2:
              ansible_host: 10.10.0.22
            db-3:
              ansible_host: 10.10.0.24
        services:
          hosts:
            harbor:
              ansible_host: 10.10.0.30
            vault:
              ansible_host: 10.10.0.31
              ansible_user: root
            tailscale:
              ansible_host: 10.10.0.40
              ansible_user: root
