all:
  children:
    k3s_cluster:
      children:
        k3s_first_server:
          hosts:
            k8s-master-1:
              ansible_host: 10.10.0.10
        k3s_servers:
          hosts:
            k8s-master-2:
              ansible_host: 10.10.0.11
            k8s-master-3:
              ansible_host: 10.10.0.12
        k3s_workers_infra:
          hosts:
            k8s-infra-1:
              ansible_host: 10.10.0.13
            k8s-infra-2:
              ansible_host: 10.10.0.14
            k8s-infra-3:
              ansible_host: 10.10.0.15
        k3s_workers_app:
          hosts:
            k8s-app-1:
              ansible_host: 10.10.0.16
            k8s-app-2:
              ansible_host: 10.10.0.17
