all:
  children:
    patroni:
      hosts:
        db-1:
          ansible_host: 10.10.0.20
        db-2:
          ansible_host: 10.10.0.22
    etcd_arbiter:
      hosts:
        db-arbiter:
          ansible_host: 10.10.0.23
    etcd:
      children:
        patroni: {}
        etcd_arbiter: {}
