all:
  children:
    patroni:
      hosts:
        db-1:
          ansible_host: 10.10.0.20
        db-2:
          ansible_host: 10.10.0.22
        db-3:
          ansible_host: 10.10.0.24
          patroni_nofailover: true
          patroni_nosync: true
    etcd:
      children:
        patroni: {}
