apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: clustersecretstore
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.path | quote }}
      version: {{ .Values.vault.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.kubernetesAuth.mountPath | quote }}
          role: {{ .Values.vault.kubernetesAuth.role | quote }}
          serviceAccountRef:
            name: {{ .Values.serviceAccountName | quote }}
            namespace: {{ .Release.Namespace | quote }}
