tempo:
  replicas: 1

  nodeSelector:
    workload: infra

  tolerations:
    - key: workload
      operator: Equal
      value: infra
      effect: NoSchedule

  persistence:
    enabled: true
    storageClassName: longhorn
    size: 10Gi

  tempo:
    retention: 72h
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      zipkin:
        endpoint: 0.0.0.0:9411

  tempoQuery:
    enabled: true
